services:
  redis:
    image: redis:latest
    container_name: redis-app
    ports:
      - "6379:6379"
    volumes:
      - ./redis_volume:/data
    # command: redis-server --appendonly yes
    command: redis-server
    restart: unless-stopped
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data: